#!/usr/bin/env bash
SCRIPT_DIR=$(cd $(dirname $0); pwd)
${SCRIPT_DIR}/dockertools/bin/new_container confluence /var/confluence
# Use the confluence user we created instead of confluence1.
VAPR_DATA_DIR_config=${SCRIPT_DIR}/confluence.config VAPR_USE_DATA_CONTAINER=TRUE ${SCRIPT_DIR}/dockertools/bin/run confluence.docker confluence bash -c "
cd /installers/confluence; wget --no-check-certificate 'https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-5.7.1-x64.bin';
sh /installers/confluence/atlassian-confluence-5.7.1-x64.bin -q -varfile /installers/confluence/response.varfile;
sed -i 's|confluence1|confluence|' /var/confluence/install/bin/user.sh;
chown -R confluence:confluence /var/confluence/*
"